# Generated by Django 3.2.9 on 2022-01-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucity', models.CharField(choices=[('Mumbai', 'mumbai'), ('Delhi', 'delhi'), ('Chennai', 'chennai'), ('Banglore', 'banglore'), ('Kolkata', 'kolkata')], default='mumbai', max_length=10)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
