# Generated by Django 3.2.9 on 2022-01-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ucity',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'mumbai'), ('Delhi', 'delhi'), ('Chennai', 'chennai'), ('Banglore', 'banglore'), ('Kolkata', 'kolkata')], default='Mumbai', max_length=10),
        ),
    ]
