# Generated by Django 3.2.9 on 2022-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220111_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'mumbai'), ('Delhi', 'delhi'), ('Chennai', 'chennai'), ('Bengaluru', 'bengaluru'), ('Kolkata', 'kolkata')], default='Mumbai', max_length=10),
        ),
    ]
